### ISSUE TITLE
Installing mapscript

### ISSUE THREAD

**Issue by Namrod21** [mapserver/mapserver#5206]
Hi !

I work with Mac OS X 10.9 and I installed mapserver 6.4 with Homebrew. Then I would like to install mapscript for Python in order to run the RT MapServer Exporter extension from QGIS. For this I used Pip:
```
sudo pip install mapscript
```

But the installation process failed:
```
mapscript_wrap.c:2564:10: fatal error: 'mapserver.h' file not found
```

However, this file exists in /usr/local/Cellar/mapserver-64/6.4.1/include/mapserver/. Then, how could I install mapscript ?

Thanks in advance four your answers !

**Comment by sdlime** [comment]
Hi @Namrod21: This is a support question that should be taken to the mapserver-users (or maybe -dev) mailing lists. Closing...

Steve
